# Generated by Django 3.1 on 2020-10-11 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20201011_1823'),
        ('wishlist', '0002_remove_wishlistitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='sizes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.size'),
        ),
    ]
