# Generated by Django 3.1 on 2020-10-11 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_wishlistitem_sizes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='sizes',
            new_name='size',
        ),
    ]
