# Generated by Django 3.1 on 2020-10-11 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20201011_1823'),
        ('wishlist', '0004_auto_20201011_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='status_bougth',
            field=models.BooleanField(default=False, verbose_name='Добавлен в корзину'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.color', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.size', verbose_name='Размер'),
        ),
    ]
