# Generated by Django 3.1 on 2020-10-11 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0005_auto_20201011_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='status_bougth',
            new_name='status_bought',
        ),
    ]
