# Generated by Django 3.1 on 2020-10-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0006_auto_20201011_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='size',
        ),
    ]
