# Generated by Django 3.1 on 2020-10-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0007_auto_20201011_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
