# Generated by Django 3.1 on 2020-10-29 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20201029_1925'),
        ('wishlist', '0008_wishlistitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='size_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wish_size_set', to='shop.sizeset'),
        ),
    ]
