# Generated by Django 3.1 on 2020-10-30 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20201029_1925'),
        ('wishlist', '0009_wishlistitem_size_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='size_set',
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='product_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_set', to='shop.productset'),
        ),
    ]
