# Generated by Django 3.1 on 2021-03-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В процессе'), ('waiting_for_capture', 'Нужно подтвердить платеж'), ('succeeded', 'Принят'), ('canceled', 'Отменен')], default='pending', max_length=50),
            preserve_default=False,
        ),
    ]
