# Generated by Django 3.1 on 2021-03-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В процессе'), ('waiting_for_capture', 'В процессе подтверждения'), ('succeeded', 'Принято'), ('canceled', 'Отменено')], default='pending', max_length=50),
        ),
    ]
