# Generated by Django 3.1 on 2020-10-10 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'купон', 'verbose_name_plural': 'купоны'},
        ),
    ]
