# Generated by Django 3.1 on 2020-11-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_simple_coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruleset',
            options={'verbose_name': 'сет правил', 'verbose_name_plural': 'сеты правил'},
        ),
        migrations.AlterModelOptions(
            name='validityrule',
            options={'verbose_name': 'правило валидации', 'verbose_name_plural': 'правила валидации'},
        ),
        migrations.AlterField(
            model_name='validityrule',
            name='expiration_date',
            field=models.DateTimeField(verbose_name='Дата истечения'),
        ),
        migrations.AlterField(
            model_name='validityrule',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активен?'),
        ),
    ]
