# Generated by Django 3.1 on 2020-11-08 11:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(default='Full description of product', help_text='Добавьте полное описание товара, без характеристик.', null=True, verbose_name='Описание'),
        ),
    ]
