# Generated by Django 3.1 on 2020-10-10 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201010_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'цвет', 'verbose_name_plural': 'цвета'},
        ),
        migrations.AlterModelOptions(
            name='colors',
            options={},
        ),
        migrations.RemoveField(
            model_name='color',
            name='color',
        ),
        migrations.RemoveField(
            model_name='color',
            name='product',
        ),
        migrations.RemoveField(
            model_name='colors',
            name='name',
        ),
        migrations.AddField(
            model_name='color',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='colors',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.color'),
        ),
        migrations.AddField(
            model_name='colors',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colors', to='shop.product'),
        ),
    ]
