# Generated by Django 3.1 on 2020-11-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201108_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productset',
            name='slug',
            field=models.SlugField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
