# Generated by Django 3.1 on 2020-11-15 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201108_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'возраст', 'verbose_name_plural': 'возрасты'},
        ),
        migrations.RemoveField(
            model_name='material',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_composition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_model',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='То как этот товар будет отображен в URL.', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.tag', verbose_name='Возраст'),
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
