# Generated by Django 3.1 on 2020-10-10 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_size_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='colors',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.size'),
        ),
    ]
