# Generated by Django 3.1 on 2020-10-10 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_colors_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colors',
            name='size',
        ),
    ]
