# Generated by Django 3.1 on 2020-10-11 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_colors_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='PriceFilterItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_filter', to='shop.pricefilter')),
            ],
        ),
    ]
