# Generated by Django 3.1 on 2020-10-11 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_pricefilter_pricefilteritem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricefilteritem',
            name='price_filter',
        ),
        migrations.DeleteModel(
            name='PriceFilter',
        ),
        migrations.DeleteModel(
            name='PriceFilterItem',
        ),
    ]
