# Generated by Django 3.1 on 2020-10-12 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0009_auto_20201012_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewresponse',
            options={'verbose_name': 'ответ на отзыв', 'verbose_name_plural': 'ответы на отзыв'},
        ),
        migrations.AddField(
            model_name='reviewresponse',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewresponse',
            name='response',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reviewresponse',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.review'),
        ),
        migrations.AddField(
            model_name='reviewresponse',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewresponse',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
