# Generated by Django 3.1 on 2020-10-13 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0010_auto_20201012_2359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewresponse',
            options={'verbose_name': 'ответ на отзыв', 'verbose_name_plural': 'ответы на отзывы'},
        ),
        migrations.AlterField(
            model_name='review',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.PositiveIntegerField(default=1, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(default='', max_length=350, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='reviewresponse',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='reviewresponse',
            name='response',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='reviewresponse',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='shop.review', verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='reviewresponse',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='reviewresponse',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Отвечающий'),
        ),
    ]
