# Generated by Django 3.1 on 2020-10-29 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20201013_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'сет товара',
                'verbose_name_plural': 'сеты товаров',
            },
        ),
        migrations.CreateModel(
            name='SizeSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='size',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='size',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='price_from',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Цена от'),
        ),
        migrations.AddField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.DeleteModel(
            name='Sizes',
        ),
        migrations.AddField(
            model_name='productset',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='shop.product'),
        ),
        migrations.AddField(
            model_name='productset',
            name='size_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='size_set', to='shop.sizeset'),
        ),
        migrations.AddField(
            model_name='size',
            name='size_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='shop.sizeset'),
        ),
    ]
