# Generated by Django 3.1 on 2020-10-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20201029_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_to',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Цена от'),
        ),
    ]
