# Generated by Django 3.1 on 2020-10-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_product_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pay_method',
            field=models.CharField(blank=True, help_text='Если почасовая-ч, по дням-д, неделям-нед.', max_length=3, null=True, verbose_name='Если аренда, то какая оплата?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rent',
            field=models.BooleanField(default=False, verbose_name='Доступно в аренду'),
        ),
    ]
