# Generated by Django 3.1 on 2020-11-06 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название для этого тэмплейта')),
                ('button', models.CharField(help_text='Максимум 2 слова с предлогом, побуждение что-то сделать, например: узнать, перейти и тд', max_length=70, null=True, verbose_name='Надпись на кнопке')),
                ('image', models.ImageField(help_text='Примерные размеры фото 1900х650, сам товар находится в правой части фото,\t\tесли разделить фото на три части двумя линиями, то товар на второй линии', upload_to='promo/first_page/images', verbose_name='Главное фото')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': '1. Главные страницы',
            },
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название для этого тэмплейта')),
                ('title_1', models.CharField(blank=True, max_length=40, null=True, verbose_name='Заголовок первой услуги')),
                ('subtitle_1', models.CharField(blank=True, max_length=40, null=True, verbose_name='Подзаголовок первой услуги')),
                ('title_2', models.CharField(blank=True, max_length=40, null=True, verbose_name='Заголовок второй услуги')),
                ('subtitle_2', models.CharField(blank=True, max_length=40, null=True, verbose_name='Подзаголовок второй услуги')),
                ('title_3', models.CharField(blank=True, max_length=40, null=True, verbose_name='Заголовок третьей услуги')),
                ('subtitle_3', models.CharField(blank=True, max_length=40, null=True, verbose_name='Подзаголовок третьей услуги')),
            ],
            options={
                'verbose_name': 'Четвертая страница',
                'verbose_name_plural': '4. Страницы услуг',
            },
        ),
        migrations.CreateModel(
            name='SubPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название для этого тэмплейта')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок страницы')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок страницы')),
            ],
            options={
                'verbose_name': 'Пятая страница',
                'verbose_name_plural': '5. Пятые страницы',
            },
        ),
        migrations.CreateModel(
            name='ThirdPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название для этого тэмплейта')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок страницы')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок страницы')),
            ],
            options={
                'verbose_name': 'Третья страница',
                'verbose_name_plural': '3. Третьи страницы',
            },
        ),
        migrations.CreateModel(
            name='SecondPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название для этого тэмплейта')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подзаголовок страницы')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок страницы')),
                ('image_for_first_cat', models.ImageField(help_text='Левая колонка 750x1050', upload_to='promo/second_page/first_category/images', verbose_name='Фото категории')),
                ('alt_for_image_no_1', models.CharField(max_length=100, null=True, verbose_name='Описание картинки 1')),
                ('image_for_second_cat', models.ImageField(help_text='Центральная колонка, верх 750x500', upload_to='promo/second_page/second_category/images', verbose_name='Фото категории')),
                ('alt_for_image_no_2', models.CharField(max_length=100, null=True, verbose_name='Описание картинки 2')),
                ('image_for_third_cat', models.ImageField(help_text='Центральная колонка, низ 750x500', upload_to='promo/second_page/third_category/images', verbose_name='Фото категории')),
                ('alt_for_image_no_3', models.CharField(max_length=100, null=True, verbose_name='Описание картинки 3')),
                ('image_for_fourth_cat', models.ImageField(help_text='Правая колонка 750x1050', upload_to='promo/second_page/fourth_category/images', verbose_name='Фото категории')),
                ('alt_for_image_no_4', models.CharField(max_length=100, null=True, verbose_name='Описание картинки 4')),
                ('first_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_no_1', to='shop.category')),
                ('fourth_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_no_4', to='shop.category')),
                ('second_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_no_2', to='shop.category')),
                ('third_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_no_3', to='shop.category')),
            ],
            options={
                'verbose_name': 'Вторая страница',
                'verbose_name_plural': '2. Вторые страницы',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=250, verbose_name='SEO Название')),
                ('seo_description', models.CharField(blank=True, max_length=250, verbose_name='SEO Описание')),
                ('theme_of_promo', models.CharField(max_length=60, verbose_name='Тема акции \n(подзаголовок на главной)')),
                ('offer', models.CharField(max_length=100, verbose_name='Оффер на главной странице')),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('is_main', models.BooleanField(default=False, verbose_name='Главный')),
                ('first_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotion.firstpage', verbose_name='Первый экран')),
                ('second_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotion.secondpage', verbose_name='Второй экран')),
                ('service_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service', to='promotion.servicepage', verbose_name='Экран услуг')),
                ('sub_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotion.subpage', verbose_name='Экран подписки')),
                ('third_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotion.thirdpage', verbose_name='Третий эран')),
            ],
            options={
                'verbose_name': 'промоушн',
                'verbose_name_plural': 'промоушны',
            },
        ),
        migrations.CreateModel(
            name='PromoProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo', to='shop.product')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='promotion.promotion')),
            ],
            options={
                'verbose_name': 'промо товар',
                'verbose_name_plural': 'промо товары',
            },
        ),
    ]
