# Generated by Django 3.1 on 2020-10-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
