# Generated by Django 3.1 on 2020-10-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_promotion_is_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promoproduct',
            options={'verbose_name': 'промо товар', 'verbose_name_plural': 'промо товары'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': 'промоушн', 'verbose_name_plural': 'промоушны'},
        ),
        migrations.RemoveField(
            model_name='promoproduct',
            name='discount',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Главный'),
        ),
    ]
