# Generated by Django 3.1 on 2020-11-04 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_auto_20201028_2039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopProducts',
        ),
    ]
