# Generated by Django 3.1 on 2020-11-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0004_secondpage_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondpage',
            name='text_no_2',
            field=models.CharField(max_length=150, null=True, verbose_name='Текст над картинкой'),
        ),
    ]
