# Generated by Django 3.1 on 2020-10-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_question_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='response',
            field=models.TextField(null=True, verbose_name='ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(null=True, verbose_name='Вопрос'),
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
