# Generated by Django 3.1 on 2020-10-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_auto_20201024_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
