# Generated by Django 3.1 on 2020-10-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_auto_20201024_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='OftenQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(null=True, verbose_name='Вопрос')),
                ('response', models.TextField(null=True, verbose_name='ответ')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'часто задаваемый вопрос',
                'verbose_name_plural': 'часто задаваемые вопросы',
            },
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
