# Generated by Django 3.1 on 2020-10-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0007_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'вопрос', 'verbose_name_plural': 'вопросы'},
        ),
        migrations.AddField(
            model_name='question',
            name='response',
            field=models.TextField(null=True, verbose_name='Ответ'),
        ),
    ]
