# Generated by Django 3.1 on 2020-10-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0008_auto_20201024_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
    ]
