# Generated by Django 3.1 on 2020-11-04 06:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0009_auto_20201028_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oftenquestion',
            name='question',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='oftenquestion',
            name='response',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='ответ'),
        ),
    ]
