# Generated by Django 3.1 on 2020-11-05 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0011_about_delivery_help_privacy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'о нас', 'verbose_name_plural': 'о нас'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'доставка', 'verbose_name_plural': 'доставка'},
        ),
        migrations.AlterModelOptions(
            name='help',
            options={'verbose_name': 'помощь', 'verbose_name_plural': 'помощь'},
        ),
        migrations.AlterModelOptions(
            name='privacy',
            options={'verbose_name': 'приватность', 'verbose_name_plural': 'приватность'},
        ),
        migrations.RemoveField(
            model_name='privacy',
            name='title',
        ),
    ]
