# Generated by Django 3.1 on 2020-11-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
