# Generated by Django 3.1 on 2020-11-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_promotion_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondpage',
            name='alt_for_image_no_3',
        ),
        migrations.RemoveField(
            model_name='secondpage',
            name='alt_for_image_no_4',
        ),
        migrations.RemoveField(
            model_name='secondpage',
            name='fourth_category',
        ),
        migrations.RemoveField(
            model_name='secondpage',
            name='image_for_fourth_cat',
        ),
        migrations.RemoveField(
            model_name='secondpage',
            name='image_for_third_cat',
        ),
        migrations.RemoveField(
            model_name='secondpage',
            name='third_category',
        ),
        migrations.AlterField(
            model_name='secondpage',
            name='image_for_first_cat',
            field=models.ImageField(help_text='Левая колонка 1125x1050', upload_to='promo/second_page/first_category/images', verbose_name='Фото категории'),
        ),
        migrations.AlterField(
            model_name='secondpage',
            name='image_for_second_cat',
            field=models.ImageField(help_text='Правая колонка 1125x1050', upload_to='promo/second_page/second_category/images', verbose_name='Фото категории'),
        ),
    ]
