# Generated by Django 3.1 on 2020-11-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_auto_20201114_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondpage',
            name='text',
            field=models.CharField(max_length=150, null=True, verbose_name='Текст над картинкой'),
        ),
    ]
