# Generated by Django 3.1 on 2020-11-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0005_secondpage_text_no_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstpage',
            name='image',
            field=models.ImageField(help_text='Примерные размеры фото 1900х650, сам товар находится в правой части фото,\t\tесли разделить фото на три части двумя линиями, то товар на второй линии', null=True, upload_to='promo/first_page/images', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='offer',
            field=models.CharField(max_length=100, null=True, verbose_name='Оффер на главной странице'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='theme_of_promo',
            field=models.CharField(max_length=60, null=True, verbose_name='Тема акции \n(подзаголовок на главной)'),
        ),
    ]
