# Generated by Django 3.1 on 2020-11-19 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0006_auto_20201119_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='third_page',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='first_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotion.firstpage', verbose_name='Первый экран'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='theme_of_promo',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Тема акции \n(подзаголовок на главной)'),
        ),
        migrations.DeleteModel(
            name='ThirdPage',
        ),
    ]
