# Generated by Django 3.1 on 2020-09-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartAddProductForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_test', models.CharField(choices=[('50', '50'), ('56', '56'), ('62', '62')], max_length=3)),
            ],
        ),
    ]
