# Generated by Django 3.1 on 2020-11-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(max_length=200, null=True, verbose_name='Мерки'),
        ),
    ]
