# Generated by Django 3.1 on 2020-10-24 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201020_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_type',
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка (%)'),
        ),
    ]
