# Generated by Django 3.1 on 2020-10-31 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20201031_2044'),
        ('orders', '0005_auto_20201031_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_product_sets', to='shop.productset'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.product'),
        ),
    ]
