# Generated by Django 3.1 on 2020-11-02 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_simple_coupons', '0001_initial'),
        ('orders', '0007_auto_20201031_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='django_simple_coupons.coupon', verbose_name='Купон'),
        ),
    ]
