# Generated by Django 3.1 on 2020-11-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dilivery_method',
            field=models.CharField(max_length=1, verbose_name='Доставка'),
        ),
    ]
